[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["Aidan <aidan.oconnor@snyk.io>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
